/* Generated by Yosys 0.36 (git sha1 cc31c6e, g++ 12.2.0 -fstack-clash-protection -mtune=generic -O2 -ffile-prefix-map=/builddir/yosys-0.36=. -fPIC -Os) */

(* top =  1  *)
(* src = "dff.v:1.1-11.10" *)
module DFlipFlop(clk, D, Q);
  (* src = "dff.v:3.16-3.17" *)
  input D;
  wire D;
  (* src = "dff.v:4.16-4.17" *)
  output Q;
  reg Q;
  (* src = "dff.v:2.16-2.19" *)
  input clk;
  wire clk;
  (* src = "dff.v:7.1-9.4" *)
  always @(posedge clk)
    Q <= D;
endmodule
